### ISSUE TITLE
Question: Purpose of 10s delay during setup in DROPIN mode?

### ISSUE THREAD

**Issue by JRVeale** [uStepper/uStepperS#16]
Question in the title. Are there any adverse effects by removing (or shortening) this delay?

**Comment by uStepper** [comment]
Hi,

The reason this delay was added initially was because during power up, when the printer controller board was connected to the uSteppers, some "garbage" signals sometimes occured on the step/dir/ena lines, making the system behave strange.

That said, this delay might not be needed in all setups, we just chose to keep it, as it was needed in our case

Best Regards,
Thomas Olsen
